# Generated by Django 3.1 on 2023-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='your_default_value_here', max_length=100),
        ),
    ]
